WIP

diff --git a/scripts/docker-backup-volume b/scripts/docker-backup-volume
--- a/scripts/docker-backup-volume
+++ b/scripts/docker-backup-volume
@@ -5,25 +5,25 @@ log () {
 }
 
 print_usage () {
-  log "USAGE: $0 <from_container> [backup_target] [archive_name]"
-  log " e.g.: $0 romantic_galois ./"
+  log "USAGE: $0 <volume_name> [backup_target] [archive_name]"
 }
 
-if [ $# -eq 0 ] || [ $# -gt 99 ]; then
+if [ $# -eq 0 ] || [ $# -gt 3 ]; then
   log "ERROR: Invalid argument count!"
-  print_usage
-  exit 127
-fi
-
-if [ -z "$1" ]; then
-  log "ERROR: Missing required argument 'from_container'!"
   print_usage
   exit 1
 fi
 
-FROM_CONTAINER="$1"
-BACKUP_TARGET="$(realpath ${2:-`pwd`})"
-ARCHIVE_NAME="${3:-backup-${FROM_CONTAINER}-`date '+%Y%m%d-%H%M%S-%Z'`.tgz}"
-MOUNT_POINTS="$(docker inspect $FROM_CONTAINER | jq -r '.[0].Mounts | .[] | .Destination')"
+if [ -z "$1" ]; then
+  log "ERROR: Missing required argument 'volume_name'!"
+  print_usage
+  exit 2
+fi
 
-exec docker run --rm --volumes-from "${FROM_CONTAINER}" -v "${BACKUP_TARGET}:/backup" alpine:latest sh -c "apk add tar &>/dev/null && tar -cvzf /backup/${ARCHIVE_NAME} $(echo "$MOUNT_POINTS" | tr '\n' ' ')"%
+VOLUME_NAME="$1"
+BACKUP_TARGET="$(realpath ${2:-`pwd`})"
+ARCHIVE_NAME="${3:-volume-backup_${VOLUME_NAME}_`date '+%Y%m%d-%H%M%S-%Z'`.tgz}"
+
+log "INFO: Backing up volume '${VOLUME_NAME}' into '${BACKUP_TARGET}/${ARCHIVE_NAME}'..."
+
+exec docker run --rm -v "${VOLUME_NAME}:/source_volume" -v "${BACKUP_TARGET}:/backup" alpine:latest sh -c "apk add tar &>/dev/null && cd /source_volume && tar -cvzf /backup/${ARCHIVE_NAME} ."
